### ISSUE TITLE
class IntEnum deserialization casting help

### ISSUE THREAD

**Issue by tomasznm** [lojack5/structured#50]
**Describe the bug**

I am serializing and deserializing a message header. Some fields have been defined as Enum to spice it up (or self-documentation). If I specify the byte_order argument to ByteOrder.LE the Enums are converted to int during deserialization. 

It works fine when byte_order is set to ByteOrder.DEFAULT.

On my machine ByteOrder.DEFAULT is ByteOrder.LE.

Why do I want to change the ByteOrder?

ByteOrder.DEFAULT has a 4-byte alignment and ByteOrder.LE has a 1-byte alignment. I need the 1-byte alignment with a little-endian byte order.

**To Reproduce**

**Not working** example:

```
from typing import Annotated
from enum import IntEnum
from structured import *

class MessageType(IntEnum):
    Nil       = 0
    Message1  = 1
    Message2  = 2
    Message3  = 3
    Message4  = 4

class Header(Structured, init=False, byte_order=ByteOrder.LE):

    def __init__(self, src = 1, dst = 2, message = MessageType.Message3):
        self.src = src
        self.dst = dst
        self.message = message

    src: uint8
    dst: uint8
    message: Annotated[MessageType, SerializeAs(uint16)]

msg = Header()
data = msg.pack()

print(msg)
print(data)

msg_out = Header()
msg_out.unpack(data)

print(msg_out)
print(msg_out.message.value)
print(msg_out.message.name)
print(data)
```

**Working** example:

```
from typing import Annotated
from enum import IntEnum
from structured import *

class MessageType(IntEnum):
    Nil       = 0
    Message1  = 1
    Message2  = 2
    Message3  = 3
    Message4  = 4

class Header(Structured, init=False, byte_order=ByteOrder.DEFAULT):

    def __init__(self, src = 1, dst = 2, message = MessageType.Message3):
        self.src = src
        self.dst = dst
        self.message = message

    src: uint8
    dst: uint8
    message: Annotated[MessageType, SerializeAs(uint16)]

msg = Header()
data = msg.pack()

print(msg)
print(data)

msg_out = Header()
msg_out.unpack(data)

print(msg_out)
print(msg_out.message.value)
print(msg_out.message.name)
print(data)
```

**Expected behaviour**

The expected behaviour would be to have Enum fields deserialized.

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Version  22.04
 - Machine Type: x86 (little-endian byte ordering)
 - Python 3.11 and 3.12

Any help or alternative way of making this work would be appreciated.

**Comment by lojack5** [comment]
Thanks for the report!

An initial look through the code didn't find an obvious problem, so I'll have to dig through some more to find where the issue is.  In the meantime, could you try:
```
message: Annotated[MessageType, SerializeAs(uint16).with_factory(MessageType)]
```
to see if that works around the issue? I have the feeling it won't, but worth a try.

**Comment by lojack5** [comment]
Ok, test out the branch [50-byte-order-fix](/lojack5/structured/tree/50-byte_order_fix), which should fix the issue.

**Comment by tomasznm** [comment]
Yes, I confirm the branch [50-byte_order_fix](https://github.com/lojack5/structured/tree/50-byte_order_fix) fixes the issue.
